### ISSUE TITLE
`jus` blir ikkje godkjent

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sme#16]
Rapport frå @leneantonsen:

<img width="357" alt="Skjermbilde 2021-03-09 kl  09 33 27" src="https://user-images.githubusercontent.com/1255285/110494957-badb9a00-80fc-11eb-8b67-ecd152fea0f2.png">

**Comment by thomasomma** [comment]
FIXED:

"<jus>"
        "jus" CS <W:0.0> @CVP SELECT:12991:jusCS MAP:13507:r11
;       "jus" N <NomGenSg> Err/Lex Sem/Domain Sg Gen <W:0.0> SUBSTITUTE:3532 SELECT:12991:jusCS
;       "jus" N <NomGenSg> Err/Lex Sem/Domain Sg Nom <W:0.0> SUBSTITUTE:3532 SELECT:12991:jusCS
;       "juss" N <NomGenSg> Err/Lex Sem/Domain Sg Gen <W:0.0> SUBSTITUTE:3532 SELECT:12991:jusCS
;       "juss" N <NomGenSg> Err/Lex Sem/Domain Sg Nom <W:0.0> SUBSTITUTE:3532 SELECT:12991:jusCS
