### ISSUE TITLE
`omd` utan punktum får irrelevant forslag

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sme#18]
Jf:

<img width="446" alt="omd-feil" src="https://user-images.githubusercontent.com/1255285/110503711-2590d380-8105-11eb-9eb1-99a9ccecc2ef.png">

**Comment by thomasomma** [comment]
FIXED:

"<omd>"
        "omd" Adv Err/Orth Sem/Txt ABBR Gram/TAbbr <W:0.0> @ADVL> MAP:23120 &typo ADD:8895:Err/Orth-any
typo
        "omd" Adv Sem/Txt ABBR Gram/TAbbr <W:0.0> @ADVL> MAP:23120 &typo &SUGGEST ADD:8895:Err/Orth-any COPY:8904:Err/Orth-any
omd+Adv+ABBR+Gram/TAbbr omd.
;       "omd" Adv Err/Orth Sem/Txt ABBR Gram/TAbbr Attr <W:0.0> REMOVE:14783:AttrVFINx
