### ISSUE TITLE
No analysis for "➤"

### ISSUE THREAD

**Issue by carges** [giellalt/lang-sme#27]
I get the following:
````
echo '➤'| hfst-tokenise --print-all --giella-cg --no-weights --unique tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 --grammar tools/tokenisers/mwe-dis.bin | cg-mwesplit | vislcg3 --grammar src/cg3/disambiguator.bin | vislcg3 --grammar src/cg3/korp.bin | vislcg3 --grammar src/cg3/dependency.bin
:➤\n
````

**Comment by snomos** [comment]
Why do you need an analysis? Does it have a significance in the text? Does it get an analysis in the regular analyser?

**Comment by Trondtr** [comment]
Fordi ukjende symbol stoppar Börre sitt skript.

Hanki Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by carges** [comment]
Det er Ciprian skriptet som stopper, den takler ikke "feil" format i analyserte tekster.
Poeng er at det som er ukjent bør komme slik:
````
<"➤"> 
        "➤" ?
`````
og ikke etter ":"

**Comment by snomos** [comment]
Uansett om det er Børre eller Ciprian sitt skript som er problemet, så bør feilen rettast der og ikkje med ein evig runddans med `*.pmscrip`-filene. Notasjonen med `: xxx` er jo nettopp _meint_ for å handtera ukjente teikn som ikkje har relevans for tekstanalysen. It’s not a bug, it’s a feature 🙂

**Comment by snomos** [comment]
Eg avsluttar denne saka, eg ser ingen grunn til å halda henne ope.
