### ISSUE TITLE
space error correction works with divvun-checker, but we get an fp when running yaml tests

### ISSUE THREAD

**Issue by lynnda-hill** [giellalt/lang-sme#35]
We ran the yaml-test real-PrtPl3-PrsSg3.yaml. There we get a false positive for the space error correction connected to "s.57-58". However, if we just run the grammar checker in the terminal (both with modes and also with divvun-checker) the correction seems to be fine. Is there an error in the yaml-test routine or is it something else?

Result of yaml-tests:

Test 871/3708: (Schnitler gihpa III, s.57-58) Dán olmmošlohkama mielde orro dan áigge 315 dáčča bearraša ja 367 mearrasámi bearraša Finnmárkkus.
----------
tools/grammarcheckers/tests/real-PrtPl3-PrsSg3.yaml
[ 871/3708][FAIL fp1] s.57-58:s. 57-58 (, ()) => s.57-58:[s. .57-58] (no-space-after-punct-mark)
tools/grammarcheckers/tests/real-PrtPl3-PrsSg3.yaml
[ 871/3708][FAIL fp2] : (, ()) => .57-58:[. 57-58] (no-space-after-punct-mark)
Test 871 - Passes: 0, Fails: 2, Total: 2

Result of divvun-checker -s $GTLANGS/lang-sme/tools/grammarcheckers/pipespec.xml|jq

    [
      "s.57-58",
      22,
      29,
      "no-space-after-punct-mark",
      "Ii leat gaska \"s.\" maŋis",
      [
        "s. 57-58"
      ],
      "Sátnegaskameattáhus"
    ],

**Comment by albbas** [comment]
There is an error in gramcheck-test.py, I'm looking at it now.
