### ISSUE TITLE
gramchk byter font/textstorlek!

### ISSUE THREAD

**Issue by duomdaamaendra** [giellalt/lang-sme#39]
Detta er teksten innan jag har tryckt på nån knapp:

<img width="1465" alt="Skjermbilde 2022-01-24 kl  03 55 31" src="https://user-images.githubusercontent.com/26539221/150756155-ea066121-2c19-4afd-b014-fbfb118c0464.png">

och så säger gramcheckern att det er fel hermetegn, och jag trycker, och då tar ordet "ruhtabursa" efter fonten tidigare i texten:

<img width="887" alt="Skjermbilde 2022-01-24 kl  10 27 54" src="https://user-images.githubusercontent.com/26539221/150756440-7f9af8c4-a746-4fa4-b6fb-abed946e78ff.png">

@unhammer 
@snomos 
@lynnda-hill 

Originaltekst:

> Su váldofágadutkamuš lei sosiálapedagogihkas, fáddán ”Samisk barneoppdragelse og kjønnssosialisering”, Oslo 1986. 
>
> «Ruhtagiehta» ja «Bállobiigá»

**Comment by duomdaamaendra** [comment]
<img width="5" alt="Skjermbilde 2022-01-24 kl  03 55 01" src="https://user-images.githubusercontent.com/26539221/150754786-56cdaa1c-11f7-48fc-8485-b8f00102bd6f.png">

**Comment by duomdaamaendra** [comment]
<img width="5" alt="Skjermbilde 2022-01-24 kl  03 55 01" src="https://user-images.githubusercontent.com/26539221/150754849-9cdec857-36e0-482d-9384-b0e5647b8122.png">

**Comment by duomdaamaendra** [comment]
<img width="5" alt="Skjermbilde 2022-01-24 kl  03 55 01" src="https://user-images.githubusercontent.com/26539221/150755148-52a80d18-c9a7-485c-86a7-c49351ac51b4.png">

detta er teksten innan jag har tryckt på nån knapp

**Comment by duomdaamaendra** [comment]
<img width="5" alt="Skjermbilde 2022-01-24 kl  03 55 01" src="https://user-images.githubusercontent.com/26539221/150755402-9273a14d-f591-408a-b8b1-198720159b9e.png">


@unhammer

**Comment by duomdaamaendra** [comment]
<img width="1420" alt="Skjermbilde 2022-01-24 kl  04 00 04" src="https://user-images.githubusercontent.com/26539221/150755846-419f144d-196e-489d-aa7a-a8e75ea2d682.png">

**Comment by duomdaamaendra** [comment]
<img width="1465" alt="Skjermbilde 2022-01-24 kl  03 55 31" src="https://user-images.githubusercontent.com/26539221/150756155-ea066121-2c19-4afd-b014-fbfb118c0464.png">

**Comment by duomdaamaendra** [comment]
och så säger gramcheckern att det er fel hermetegn, och jag trycker, och då tar ordet "ruhtabursa" efter fonten tidigare i texten:

**Comment by duomdaamaendra** [comment]
<img width="887" alt="Skjermbilde 2022-01-24 kl  10 27 54" src="https://user-images.githubusercontent.com/26539221/150756440-7f9af8c4-a746-4fa4-b6fb-abed946e78ff.png">

**Comment by unhammer** [comment]
Kva for program er dette – google docs?

**Comment by unhammer** [comment]
> grammatikkontrollkoden

meiner du libdivvun? Kunne du (ev. nokon som jobbar med dei pluginane) henta ut det som blir sendt som input til libdivvun i så fall?

**Comment by snomos** [comment]
Hm, no er eg ikkje i stand til å reprodusera feilen. Og https://github.com/divvun/divvun-gramcheck-web/issues/51 tyder jo på at feilen ikkje ligg i `libdivvun`.

**Comment by duomdaamaendra** [comment]
@lynnda-hill

**Comment by snomos** [comment]
Dette problemet ser ut til å vera løyst no, i alle fall så oppfører grammatikkontrollen seg rett når eg testar med testdata frå lenger opp i diskusjonen. Eg avsluttar.
