### ISSUE TITLE
GDocs marks AND fixes on wrong place when word or sign is in many places

### ISSUE THREAD

**Issue by duomdaamaendra** [giellalt/lang-sme#41]
<img width="1545" alt="Skjermbilde 2022-01-25 kl  17 42 36" src="https://user-images.githubusercontent.com/26539221/151021031-95b20488-d078-4cf2-82f4-e7e6f17c6ddd.png">

@snomos 
@lynnda-hill

**Comment by duomdaamaendra** [comment]
@snomos 
@lynnda-hill

**Comment by snomos** [comment]
Hei @duomdaamaendra Kan du lima inn heile teksten som du har teksta med, slik at andre kan testa og reprodusera? Det er viktig at det er i alle fall er så mykje tekst at det blir to tilfelle av det same ordet med feil i (*imprešonisttalaš* i dette tilfellet). Elles blir det uråd å reprodusera :)

**Comment by duomdaamaendra** [comment]
Sámis gávdno juoga mii sulastahttá girjjálašvuođa árvvoštallama. Ellen Marie Vars «Kátjá» romána omd. lea maŋemuš jagiid ožžon stuorámus fuobmášumi go oppa njeallje árvvoštalli čálle girjji birra. Ieš guđet sivain sii dadjet girji lei buorre ja čálli lei čeahppi, muhto dattege – dađe čiekŋaleabbo girjjálašvuođa árvvoštallamat gal eai lean. Dát árvvoštallan lea buorre ovdamearkan diekkár čuoččuhussii.
«Jo girjji vuosttas siiddu logadettiin badjána millii mot/movt duot rohkkes Láhpoluobbala gollenieida čálligoahtá jo álggus maid son buoremusat dovdá, namalassii: luonddu ja čakčabiekkaid garasvuođa birra.» (Sámi Áigi, 20.b. guovvam. 1987.)
Árvvoštalli resymere dasto sisdoalu (40% čállosis), maiddái soames ovdamearkkaiguin (oanehis sitátaiguin), ja geavaha loahpa kommenteret romána giela. Dás daddjo omd. ahte «-giellaárvu lea syntáktalaččat ja sátneriggodaga dáfus njunušjin.» [109] Berre gal namahastit ahte árvvoštalli parantesa siste dadjala ahte ii sutnje gula sisdoalu veardidit. Ja dasto berre dás daddjot ahte árvvoštalli goit rábmo, ii dušše čálli, muhto maiddái girjji – ja dalle várra giellaeavttuid vuođul.
Vaikko vel čájehuvvon árvvoštallama ii gohčodivčče girjjálašvuođa árvvoštallamin, de dat goit muitala ahte sámi girjjit árvvoštallojit sámi mediain. Árvvoštallamiid dárkileabbo guorahallan nuolaha gal eatnašid oalle álásin mii guoská árvvoštalliid dieđuide girjjálašvuođa ja girjjálaš proseassaid birra. Árvvoštallamat leat dadjat dušše subjektiivvalaččat, ja dovdduide vuođđuduvvon – ja eai buot áiggiid dalle ge doarvái bures ággaduvvon go omd. ii čielgga manne liikui dahje ii liikon girjái. Árvvoštallan sáhttá de šaddat dušše árvvoštalli sátnestoahkamin girjjálašvuođa árvvoštallama haga. Ieš árvvoštallan šattai goit čálusin mii lea fas ovdamearkan sámi girjjálašvuhtii ja man fas sáhttá ja oažžu árvvoštallat eavttuiguin ja gaskaomiiguin mat dasa gullet. (Mun geavahan dás sáni eaktu/eavttut gokčat dárogielat sáni «kriterie».)
Árvvoštallanvuogit
Girjjálašvuođa árvvoštallama historjjás diehtit ahte leat iešguđet árvvoštallanvuogit geavahuvvon. Dávjá leat ovtta vuogi hutkit ja geavaheaddjit garrasit čuoččuhan ahte eará vuogit eai leat duođalaččat ja anulaččat, earret vuohki man sii ovddastit. Nu lea maŋŋa máilmmesoađi nu gohčoduvvon anglo-amerihkalaš New Criticism leamaš garra váikkuheaddjin, man sadjái fas odne lea poststrukturalisttalaš vuohki alcces čorgen saji, man dieđusge lea maiddái ideologalaš árvvoštallanvuohki garrasit váikkuhan. Dattege namahuvvojit omd. dážas eanaš árvvoštallit áviissain odne dábáleamosit impresjonisttalaš árvvoštallin. Nu maiddái gohčodivččii erenoamážit eanaš sámi árvvoštalliid.

**Comment by duomdaamaendra** [comment]
3 x imprešonisttalaš no!

**Comment by duomdaamaendra** [comment]
@lynnda-hill

**Comment by lynnda-hill** [comment]
> <img alt="Skjermbilde 2022-01-25 kl 17 42 36" width="1545" src="https://user-images.githubusercontent.com/26539221/151021031-95b20488-d078-4cf2-82f4-e7e6f17c6ddd.png">
> 
> @snomos @lynnda-hill

in the terminal the following is suggested:

"<imprešonisttalaš>"
        "impresjonista" Ex/N Sem/Hum Der/lasj A Attr <W:67.3018> <WA:27.3018> <spelled> "impresjonisttalaš"S PROTECT:3480 SELECT:3636:SoriaMoria SELECT:1281 &SUGGESTWF &typo #11->11 ADD:10058:spelled
typo
;       "impresjonista" Ex/N Sem/Hum Der/lasj A Sg Nom <W:67.3018> <WA:27.3018> <spelled> "impresjonisttalaš"S PROTECT:3480 SELECT:3636:SoriaMoria SELECT:1281
;       "imprešonisttalaš" ? SELECT:3636:SoriaMoria
: 
"<árvvoštallin>"
        "árvvoštallat" Ex/V TV <AG-Nom-Ani> <TH-FS-Qpron> Der/NomAg N Ess <W:0.0> SUBSTITUTE:2542 SUBSTITUTE:3329 @<SPRED MAP:23116:HNOUN<spred3 #12->12
        "árvvoštallat" Ex/V TV <AG-Nom-Ani> <TH-FS-Qpron> Der/NomAg N Sg Loc South Err/Orth <W:0.0> SUBSTITUTE:2542 SUBSTITUTE:3329 @<ADVL MAP:23265 #12->12
        "árvvoštalli" N NomAg Sem/Hum Ess <W:0.0> @<SPRED MAP:23116:HNOUN<spred3 #12->12
        "árvvoštalli" N NomAg Sem/Hum Sg Acc Err/Orth PxSg1 <W:0.0> @<OBJ MAP:23922:IfNoTransV> #12->12
        "árvvoštalli" N NomAg Sem/Hum Sg Gen Err/Orth PxSg1 <W:0.0> @<ADVL MAP:23334:r520 #12->12
        "árvvoštalli" N NomAg Sem/Hum Sg Loc South Err/Orth <W:0.0> @<ADVL MAP:23265 #12->12
"<.>"
        "." CLB <W:0.0> #13->13
:

**Comment by snomos** [comment]
Denne feilen er no endeleg retta!! Juhu! 🙂
