### ISSUE TITLE
Word doesn't recognize perfectly fine word

### ISSUE THREAD

**Issue by duomdaamaendra** [giellalt/lang-sme#42]
<img width="1567" alt="Skjermbilde 2022-01-26 kl  02 47 26" src="https://user-images.githubusercontent.com/26539221/151089833-8f2a5b26-c712-4344-9da6-8e9f1f1994ad.png">

**Comment by duomdaamaendra** [comment]
the word is recognized in Googledocs, and here analyze in terminal:
"<muhtunlágán>"
        "muhtunlágan" A Sem/Dummytag v2 Attr <W:0.0> @>N SELECT:15576:r1785 SELECT:15025:AAttrCop MAP:22327:r86 #46->46
;       "muhtunlágan" A Sem/Dummytag v2 Sg Acc Err/Orth-nom-acc <W:0.0> SELECT:15576:r1785
;       "muhtunlágan" A Sem/Dummytag v2 Sg Gen Err/Orth-nom-gen <W:0.0> SELECT:15576:r1785
;       "muhtunlágan" A Sem/Dummytag v2 Sg Nom <W:0.0> SELECT:15576:r1785 SELECT:15025:AAttrCop

**Comment by duomdaamaendra** [comment]
@snomos

**Comment by duomdaamaendra** [comment]
one more example, the same fenomenom:
<img width="1587" alt="Skjermbilde 2022-01-26 kl  02 58 04" src="https://user-images.githubusercontent.com/26539221/151090994-00534fe9-5ee6-4308-8bb1-57c75b94d2c3.png">

**Comment by duomdaamaendra** [comment]
@snomos

**Comment by duomdaamaendra** [comment]
@lynnda-hill

**Comment by lynnda-hill** [comment]
everything fine in the terminal...

**Comment by duomdaamaendra** [comment]
functions in new version
