### ISSUE TITLE
GramDivvun speller suggestion regression - no suggestions where it used to be

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sme#43]
Cf https://github.com/divvun/divvun-gramcheck-web/issues/18

This also be related to the discussion in https://github.com/divvun/libdivvun/issues/33.

**Comment by snomos** [comment]
What a lousy bug report by me - no data to reproduce and test on. Shame on you, @snomos

**Comment by unhammer** [comment]
Is this https://github.com/divvun/divvun-gramcheck-web/issues/18 which was in the editor plugins?

**Comment by snomos** [comment]
Might be. We'll see soon, as a fix to that one is to be released soon.

**Comment by snomos** [comment]
Closing this one, as there is no way to fix a problem that isn't properly described and thus not reproducible.
