### ISSUE TITLE
Missing remove-derivation-strings.nob.hfst in apertium/filters

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-sme#432]
With `./configure --enable-tokenisers --without-xfst --enable-spellers --enable-hfst-mobile-speller --enable-alignment --disable-minimised-spellers --enable-syntax --enable-analysers --enable-generators --enable-apertium --enable-grammarchecker --enable-dicts --enable-oahpa --enable-morpher --disable-hfst-desktop-spellers` and `make -j11` the build results in:

```
make[5]: Entering directory '/build/giella-sme-0.2.0+g33192~4581d39a-1~sid1/tools/mt/apertium/filters'
"/usr/bin/hfst-regexp2fst"  --format=foma \
	 -v -S remove-derivation-strings-modifications.nob.regex -o remove-derivation-strings-modifications.nob.hfst
make[5]: *** No rule to make target 'remove-derivation-strings.nob.hfst', needed by 'all-am'.  Stop.
```

**Comment by flammie** [comment]
heh I already had it fixed but uncommited
