### ISSUE TITLE
msword (wrongly) suggest space, then after correction suggests no space in same place

### ISSUE THREAD

**Issue by duomdaamaendra** [giellalt/lang-sme#49]
<img width="1588" alt="Skjermbilde 2022-01-31 kl  06 08 09" src="https://user-images.githubusercontent.com/26539221/151742060-14d1831b-84f6-4a82-8427-e7e33ca02dbe.png">

after correction to space:

<img width="1588" alt="Skjermbilde 2022-01-31 kl  06 08 35" src="https://user-images.githubusercontent.com/26539221/151742068-83b4b83d-df6a-4fd9-9bcc-06afb7e6d7db.png">

**Comment by duomdaamaendra** [comment]
Ahte čálli ovddit bargguid lea miellagiddevaš ja dehálaš veardidit ođđa girjjiin ii dárbbaš eahpidit. Girjjálašvuođa árvvoštalli han galggašii fuobmát ja diehtit, buorebut go okta ge eará, mo lea omd. girječálli ovdáneapmi ovddeš čállosiid ektui. Leat go čálli ođđa barggus ovddeš temát eambbo ja čiekŋaleappot meannuduvvon omd.? Dát dieđut ge leat dehálaččat boahttevaš girjelohkkái. Dáža girjjálašvuođa árvvoštallamis omd. bidjet dása lossa deattu.

**Comment by duomdaamaendra** [comment]
Googledocs handles it a little bit differently. Here the result is "omd. ??", ie it puts in a space like requested + an extra question mark! Like MSword it also now says that there shouldn't be any space, but there is no green frame to go through with the correction:

<img width="441" alt="Skjermbilde 2022-01-31 kl  06 20 40" src="https://user-images.githubusercontent.com/26539221/151742826-acf4846b-ab94-41bc-a408-6e21d534e464.png">

**Comment by duomdaamaendra** [comment]
here is somewhat the same behavior in Googledocs, difference is that it is about the word "leat" an that it is about kongruens:

<img width="1431" alt="Skjermbilde 2022-01-31 kl  15 13 55" src="https://user-images.githubusercontent.com/26539221/151809552-e4b7fd92-4f2e-45a9-aa09-df442783e409.png">

And then it goes on and says the same over and over again and you can add as many "t"s as you want, it never seems to give up:

<img width="1447" alt="Skjermbilde 2022-01-31 kl  15 21 48" src="https://user-images.githubusercontent.com/26539221/151810353-fa23c18c-d6c7-4a01-b0c9-c965d94282a3.png">

**Comment by duomdaamaendra** [comment]
Loahpaheapmi
Ii dáidde leat vuos odne, go ain leat hárjehallamin, riekta gáibidit sámi girjjálašvuođa árvvoštalliin seammá go maid lunddolaččat dagašii davviriikkain muđuid mii guoská girjjálašvuođa árvvoštallamiid dássái. Mii fertet dohkkehit ahte dásage dárbbaša [124] oahpu, erenoamážit maiddái teorehtalaš oahpu. Buot surggiin ja dásiin Sámi servodagas rahčet odne garrasit ahte loktet máhtolašvuođa dási. Muhtun surggiin váilot oppalohkái iežamet návccat.

**Comment by lynnda-hill** [comment]
> <img alt="Skjermbilde 2022-01-31 kl 06 08 09" width="1588" src="https://user-images.githubusercontent.com/26539221/151742060-14d1831b-84f6-4a82-8427-e7e33ca02dbe.png">
> 
> after correction to space:
> 
> <img alt="Skjermbilde 2022-01-31 kl 06 08 35" width="1588" src="https://user-images.githubusercontent.com/26539221/151742068-83b4b83d-df6a-4fd9-9bcc-06afb7e6d7db.png">

This one should be fixed now. I added to a set where period and another punctuation mark is ok without a space. Not sure how that looks like in GoogleDocs

**Comment by lynnda-hill** [comment]
> here is somewhat the same behavior in Googledocs, difference is that it is about the word "leat" an that it is about kongruens:
> 
> <img alt="Skjermbilde 2022-01-31 kl 15 13 55" width="1431" src="https://user-images.githubusercontent.com/26539221/151809552-e4b7fd92-4f2e-45a9-aa09-df442783e409.png">
> 
> And then it goes on and says the same over and over again and you can add as many "t"s as you want, it never seems to give up:
> 
> <img alt="Skjermbilde 2022-01-31 kl 15 21 48" width="1447" src="https://user-images.githubusercontent.com/26539221/151810353-fa23c18c-d6c7-4a01-b0c9-c965d94282a3.png">

This one is weird. When testing in the terminal no error is marked.
