### ISSUE TITLE
`hiluid háluid` med feilanalyse i grammatikkontrollen

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-sme#53]
@duomdaamaendra meldte denne feilen i Zulip:

```sh
echo hiluid háluid | hfst-lookup -q src/analyser-gt-desc.hfstol
hiluid háluid hiluid háluid+Adv 0,000000
```

Denne analysen er rett. Det er derimot ikkje denne:

```sh
echo hiluid háluid | hfst-lookup -q src/analyser-gramcheck-gt-desc.hfstol
hiluid háluid hiluid háluid+Err/Orth+Adv+Err/SpaceCmp 0,000000
hiluid háluid hiluid háluid+MWE+Adv 0,000000
```

Problemet er den ekstra analysen:

```
hiluid háluid hiluid háluid+Err/Orth+Adv+Err/SpaceCmp 0,000000
```

Her er dei relevante lexc-oppføringane:

```
hiluid% háluid+Err/Orth:hiluid9-hálujd9 adv ;
hiluid% háluid+Err/MissingSpace:hiluid9∑#hálujd9 adv ; !
hiluid% háluid+MWE:hiluid% hálujd9 adv ;
hiluid% háluid+MWE+Err/Orth-a-á:hiluid% halujd9 adv ;
```

Korleis kjem feilanalysen inn i grammatikkontrollanalysatoren?

**Comment by lynnda-hill** [comment]
modes/trace-smegramrelease-dev.mode gir meg følgende:


"<hiluid háluid>"
        "hiluid háluid" Adv <W:0.0> <firstCohort> #1->1 SUBSTITUTE:10263
;       "hiluid háluid" Err/Orth Adv Err/SpaceCmp <W:0.0> <firstCohort> REMOVE:2314:mwe
"<.>"

**Comment by snomos** [comment]
Fixed in 70ae371706d1488ece4d44ea9b731515a973a76b.
