### ISSUE TITLE
fst kicks out negation verb reading in favor of a Roman number reading

### ISSUE THREAD

**Issue by lynnda-hill** [giellalt/lang-sme#56]
When running the following command, something strange happens with the analysis of the negation verb. What is wrong here?

echo 'Ii leat nu ahte sii geat heitet joatkkaskuvllas eai leat ekonomalaččat aktiivvat. ' | hfst-tokenise -g tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | divvun-blanktag tools/grammarcheckers/analyser-gt-whitespace.hfst | vislcg3 -g tools/grammarcheckers/mwe-dis.bin | vislcg3 --trace -g src/cg3/disambiguator.cg3

"<Ii>"
	"II" Num Rom Sg Nom <W:0.0> <firstCohort> <sme> ADD:2178:sme
: 
"<leat>"
	"leat" V IV Ind Prs Pl3 <W:0.0> <sme> @+FMAINV ADD:2178:sme MAP:9566:+FMAINVCop
;	"leat" V IV Ind Prs ConNeg <W:0.0> <sme> ADD:2178:sme REMOVE:4777:muhtoNotConNeg
;	"leat" V IV Ind Prs Pl1 <W:0.0> <sme> @+FMAINV ADD:2178:sme MAP:9566:+FMAINVCop REMOVE:14584:Pl1
;	"leat" V IV Ind Prs Sg2 <W:0.0> <sme> @+FMAINV ADD:2178:sme MAP:9566:+FMAINVCop REMOVE:13735:r2915
;	"leat" V IV Inf <W:0.0> <sme> ADD:2178:sme REMOVE:8631:Inf
:

**Comment by albbas** [comment]
Works on my machine (Mac, up to date lang-sme, giella-core, shared-smi and shared-mul)
```
echo 'Ii leat nu ahte sii geat heitet joatkkaskuvllas eai leat ekonomalaččat aktiivvat. ' | hfst-tokenise -g tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | divvun-blanktag tools/grammarcheckers/analyser-gt-whitespace.hfst | vislcg3 -g tools/grammarcheckers/mwe-dis.bin | vislcg3 --trace -g src/cg3/disambiguator.cg3
"<Ii>"
	"ii" V IV Neg Ind Sg3 <W:0.0> <firstCohort> <sme> @+FAUXV ADD:2178:sme MAP:9081:+FAUXVNeg
;	"II" Num Rom Sg Nom <W:0.0> <firstCohort> <sme> ADD:2178:sme REMOVE:2367:Rom
: 
"<leat>"
	"leat" V IV Ind Prs ConNeg <W:0.0> <sme> @-FMAINV ADD:2178:sme SELECT:6822:ConNegIfNeg MAP:9684:-FMAINVConNeg
;	"leat" V IV Ind Prs Pl1 <W:0.0> <sme> ADD:2178:sme SELECT:6822:ConNegIfNeg
;	"leat" V IV Ind Prs Pl3 <W:0.0> <sme> ADD:2178:sme SELECT:6822:ConNegIfNeg
;	"leat" V IV Ind Prs Sg2 <W:0.0> <sme> ADD:2178:sme SELECT:6822:ConNegIfNeg
;	"leat" V IV Inf <W:0.0> <sme> ADD:2178:sme SELECT:6822:ConNegIfNeg
: 
```

**Comment by lynnda-hill** [comment]
It looks good to me too now, so I'll close the bug
