### ISSUE TITLE
divvun-checker concatenates potential compound words

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-sme#60]
Denne feilen er først rapportert på: divvun/libdivvun#56

```bash
$ echo "soađi áigi" | divvun-checker -l se
{"errs":[],"text":"soađiáigi"}
```
Dette skjer et eller annet sted i smegram-pipelinen.

**Comment by snomos** [comment]
Dette burde tilsvara kommandoen din, men gjev eit heilt anna resultat:

```sh
 echo "soađi áigi" | ./modes/smegramrelease.mode 
"<soađi>"
	"soahti" N Sem/Event Sg Gen <W:0.0> <LastCohort> <firstCohort> @>N
"<áigi>"
	"áigi" N Sem/Time Sg Nom <W:0.0> <LastCohort> <firstCohort> @HNOUN
:\n
```

**Comment by snomos** [comment]
Med identisk kommando får eg same feil:

```sh
echo "soađi áigi" | divvun-checker -a se.zcheck 
{"errs":[],"text":"soađiáigi"}
```

**Comment by snomos** [comment]
@unhammer eller @flammie ser de kva som går feil her?

**Comment by unhammer** [comment]
før
`$ echo skuvla busse|divvun-checker -l se
{"errs":[],"text":"skuvlabusse"}
`
etter:
`
$ echo skuvla busse|divvun-checker -l se
{"errs":[],"text":"skuvla busse"}
`
ser sånn ut :)

**Comment by albbas** [comment]
Ja :)

**Comment by snomos** [comment]
Eg avsluttar saka, ho er løyst.
