### ISSUE TITLE
Make with  --enable-all-tools fails

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-sme#70]
After `./configure --enable-all-tools --enable-phonetic`, make fails with this result:

```
Making all in tts
Making all in .
  CG3COMP  disambiguator.bin
disambiguator.cg3: Error: Cannot stat semsets.cg3 due to error -1 - bailing out!
make[3]: *** [disambiguator.bin] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by albbas** [comment]
It seems that semsets.cg3 should be copied in from src/cg3 or something like that

**Comment by flammie** [comment]
copied the handling from other tools in https://github.com/giellalt/lang-sme/commit/3859fed54b7ec3763915a7555a8ca719b9397a1f
