### ISSUE TITLE
Typo suggestions missing from Grammar Checker for MS Word 

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-sme#9]
To repeat:
Take Saami text, replace all á with a, copy into Divvun Grammar Checker for MSW, and do Check.
 
The word "sahka" is marked as typo, but without spelling suggestion. se.zhfst gives intended correction:
echo sahka|hfst-ospell -S -n 5 tools/spellcheckers/se.zhfst
"sahka" is NOT in the lexicon:
Corrections for "sahka":
sáhka    14.239258
sahká    21.301800
lahka    29.587891
 
Checking for a longer text, and replacing all á with a, the following pattern emerges:
(this was my way of getting a testcorpus: 
ccat -l sme ~/boundcorpus/converted/sme/news|head -10000|tail -100|tr 'á' 'a'|see)

- All typos containing no other Saami letters than á get suggestions
- All typos without suggestions lack Saami letters (except the á that was changed to a for the test)
- one word with only á/a error get a suggestion.
- In all the cases with missing suggestions, the hfst-ospell command line speller gives the correct feedback.

Words without suggestion:
sahka (sáhka), aigi (áigi), lavlut (lávlut), jahkka (jáhkka), geahpadussan (geahpádussan)
Words with suggestion:
šadda (šaddá), earenoamažin (earenožmážin), ... 
lavlaga (lávlaga)

I test on MS Word 16.41 for Mac. It flags "nuvviDspeller" as wrong, but does not correct it, so I do not know the version of the online speller.

**Comment by snomos** [comment]
Dette er ikkje eit (stort) problem lenger. Same test repetert viser at dei aller fleste skrivefeila som blir funne får retteforslag, og som regel berre eitt (med `á` sett inn att). Her er kommandoen eg nytta:

```shell
ccat -l sme ../corpus-sme-x-closed/converted/news/ | head -10000 | tail -100 | tr 'á' 'a'
```

Deretter limte eg inn teksten i Word, og køyrde grammatikkontrollen der.

Det er framleis smårusk i forslaga, så det kan vera nyttig å køyra testen på nytt for å finna andre område å forbetra (@lynnda-hill , @duomdaamaendra ), men i høve til den feilen som vart meldt her er han løyst. Eg lukkar.

![image](https://github.com/giellalt/lang-sme/assets/1255285/4ee77d2c-3df4-4a1d-943e-bb962a5a0730)
